package example

import estype "github.com/ngicks/elastic-type/es_type"

// Types generated by ../object_test.go
// TODO: make generators, avoid manual copy and paste.

type Sample struct {
	Manager Manager `json:"manager"`
}

type Manager struct {
	Age  *int32 `json:"age"`
	Name Name   `json:"name"`
}

type Name struct {
	First string    `json:"first"`
	Last  *[]string `json:"last"`
}

type SampleRaw struct {
	Manager estype.Field[ManagerRaw] `json:"manager"`
}

type ManagerRaw struct {
	Age  estype.Field[int32]   `json:"age"`
	Name estype.Field[NameRaw] `json:"name"`
}

type NameRaw struct {
	First estype.Field[string] `json:"first"`
	Last  estype.Field[string] `json:"last"`
}
